# The URL the site will be built for
base_url = "https://martihomssoler.github.io/"
# Whether to automatically compile all Sass files in the sass directory
compile_sass = true
# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true
# The default language; used in feeds.
default_language = "en"

[search]
# Use elasticlunr for client-side search functionality
index_format = "elasticlunr_json"

[markdown]
highlight_code = true
highlight_theme = "one-dark"
render_emoji = true
external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true
smart_punctuation = true
bottom_footnotes = true
insert_anchor_links = "right"

[extra]
# Put all your custom variables here
