name: Build and Deploy to GitHub Pages
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: tailwindcss_build
        run: |
             curl -sLO https://github.com/tailwindlabs/tailwindcss/releases/download/v3.2.4/tailwindcss-linux-x64
             chmod +x tailwindcss-linux-x64
             mv tailwindcss-linux-x64 /usr/local/bin/tailwindcss
             tailwindcss -i static/input.css -o static/output.css --minify
      - name: build_and_deploy
        uses: shalzz/zola-deploy-action@master
        env:
          PAGES_BRANCH: gh-pages
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
